<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" ignored="0" total="2" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="21163" started-at="2018-06-04T20:53:43Z" finished-at="2018-06-04T20:54:04Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="21163" started-at="2018-06-04T20:53:43Z" finished-at="2018-06-04T20:54:04Z">
      <class name="com.practice.java.selenium.qa.pages.BrokenLinkTest">
        <test-method status="PASS" signature="initilizeBase()[pri:0, instance:com.practice.java.selenium.qa.pages.BrokenLinkTest@3ffc5af1]" name="initilizeBase" duration-ms="6552" started-at="2018-06-04T20:53:43Z" finished-at="2018-06-04T20:53:50Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- initilizeBase -->
        <test-method status="FAIL" signature="verifyBrokenLink()[pri:0, instance:com.practice.java.selenium.qa.pages.BrokenLinkTest@3ffc5af1]" name="verifyBrokenLink" duration-ms="14531" started-at="2018-06-04T20:53:50Z" depends-on-methods="com.practice.java.selenium.qa.pages.BrokenLinkTest.initilizeBase" finished-at="2018-06-04T20:54:04Z">
          <exception class="java.net.MalformedURLException">
            <message>
              <![CDATA[unknown protocol: javascript]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.net.MalformedURLException: unknown protocol: javascript
at java.net.URL.<init>(Unknown Source)
at java.net.URL.<init>(Unknown Source)
at java.net.URL.<init>(Unknown Source)
at com.practice.java.selenium.qa.pages.BrokenLinkTest.verifyBrokenLink(BrokenLinkTest.java)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.net.MalformedURLException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- verifyBrokenLink -->
      </class> <!-- com.practice.java.selenium.qa.pages.BrokenLinkTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
